# Generated by Django 5.2.6 on 2025-09-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nro de tienda')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la tienda')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL de foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
