# Generated by Django 5.2.6 on 2025-09-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.CharField(default=None, max_length=40, verbose_name='Dueño de la tienda'),
        ),
    ]
