# Generated by Django 5.2.6 on 2025-09-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenadas'),
        ),
    ]
