# Generated by Django 5.2.6 on 2025-09-18 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
        ('mascota', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoption',
            options={'verbose_name': 'Adopción', 'verbose_name_plural': 'Adopciones'},
        ),
        migrations.AlterField(
            model_name='adoption',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions', to='usuarios.userprofile', verbose_name='Adoptante'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions', to='mascota.pet', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Disponible'), ('pending', 'Pendiente'), ('adopted', 'Adoptado')], max_length=10, null=True, verbose_name='Estado'),
        ),
    ]
