# Generated by Django 5.2.6 on 2025-09-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_alter_adoption_options_alter_adoption_adopter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='message',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Mensaje'),
        ),
    ]
