# Generated by Django 5.2.6 on 2025-09-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_alter_adoption_message'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='adopter',
        ),
        migrations.AddField(
            model_name='adoption',
            name='adopterEmail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email del adoptante'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='adopterName',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre del adoptante'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='adopterPhone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del adoptante'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_adoptions', to='usuarios.userprofile', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
