# Generated by Django 5.2.6 on 2025-09-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_remove_adoption_adopter_adoption_adopteremail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='status',
        ),
    ]
