# Generated by Django 5.2.6 on 2025-09-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_remove_adoption_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='responsable',
        ),
    ]
