# Generated by Django 5.2.6 on 2025-09-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_remove_adoption_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leído por responsable'),
        ),
    ]
