# Generated by Django 5.2.6 on 2025-09-20 16:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('veterinaria', 'Veterinaria'), ('peluqueria', 'Peluquería'), ('spa', 'Spa')], max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('consultPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('owner', models.CharField(default=None, max_length=40, verbose_name='Dueño del servicio')),
                ('services', models.TextField(blank=True, max_length=200, null=True, verbose_name='Servicios')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL de foto')),
                ('horarioStart', models.TimeField(blank=True, null=True, verbose_name='Horario de apertura')),
                ('horarioEnd', models.TimeField(blank=True, null=True, verbose_name='Horario de cierre')),
                ('specialties', models.TextField(blank=True, max_length=200, null=True, verbose_name='Especialidades')),
                ('valoration', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='Valoración')),
                ('comments', models.TextField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Comentarios')),
            ],
        ),
    ]
