# Generated by Django 5.2.6 on 2025-09-20 17:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('veterinaria', 'Veterinaria'), ('peluqueria', 'Peluquería'), ('spa', 'Spa')], max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('consultPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('owner', models.CharField(default=None, max_length=40, verbose_name='Dueño del servicio')),
                ('services', models.TextField(blank=True, max_length=200, null=True, verbose_name='Servicios')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL de foto')),
                ('horarioStart', models.TimeField(blank=True, null=True, verbose_name='Horario de apertura')),
                ('horarioEnd', models.TimeField(blank=True, null=True, verbose_name='Horario de cierre')),
                ('specialties', models.TextField(blank=True, max_length=200, null=True, verbose_name='Especialidades')),
                ('valoration', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='Valoración')),
                ('comments', models.TextField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Comentarios')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenadas')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de reseña')),
                ('user', models.CharField(max_length=40, verbose_name='Usuario')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valoración')),
                ('comment', models.TextField(max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salud.serviceshealth', verbose_name='Servicio de salud')),
            ],
        ),
    ]
