# Generated by Django 5.2.6 on 2025-09-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceshealth',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='serviceshealth',
            name='valoration',
        ),
    ]
