# Generated by Django 5.2.6 on 2025-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0002_serviceshealth_delete_veterinaryclinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshealth',
            name='comments',
            field=models.TextField(blank=True, editable=False, max_length=1000, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='serviceshealth',
            name='valoration',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='Valoración'),
        ),
    ]
