# Generated by Django 5.2.6 on 2025-09-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0002_remove_serviceshealth_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
    ]
