# Generated by Django 5.2.6 on 2025-09-19 04:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0003_alter_serviceshealth_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshealth',
            name='consultPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
