# Generated by Django 5.2.6 on 2025-09-23 23:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0003_remove_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valoración'),
        ),
    ]
