# Generated by Django 5.2.6 on 2025-09-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0004_alter_serviceshealth_consultprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceshealth',
            name='owner',
            field=models.CharField(default=None, max_length=40, verbose_name='Dueño del servicio'),
        ),
    ]
