# Generated by Django 5.2.6 on 2025-09-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0004_reviews_email_alter_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceshealth',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='serviceshealth',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='serviceshealth',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
