# Generated by Django 5.2.6 on 2025-09-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0005_remove_serviceshealth_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceshealth',
            name='services',
        ),
        migrations.RemoveField(
            model_name='serviceshealth',
            name='specialties',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serviceshealth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salud.serviceshealth')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serviceshealth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='salud.serviceshealth')),
            ],
        ),
    ]
