# Generated by Django 5.2.6 on 2025-09-18 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Meztizo', max_length=50, verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='pet',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_pets', to='usuarios.userprofile', verbose_name='ID de la persona que publica'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra'), ('unknown', 'Desconocido')], default='unknown', max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ubication',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vacunas',
            field=models.BooleanField(default=False, verbose_name='Vacunas'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pets', to='usuarios.userprofile'),
        ),
    ]
