# Generated by Django 5.2.6 on 2025-09-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_animals_alter_pet_id_pet_tipoanimal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
