# Generated by Django 5.2.6 on 2025-09-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_remove_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
    ]
