# Generated by Django 5.2.6 on 2025-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_animals_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AddField(
            model_name='pet',
            name='idPet',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la mascota'),
        ),
    ]
