# Generated by Django 5.2.6 on 2025-09-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_remove_pet_id_pet_idpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Mestizo', max_length=50, verbose_name='Raza'),
        ),
    ]
