# Generated by Django 5.2.6 on 2025-09-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_alter_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='desparasitacion',
            field=models.BooleanField(default=False, verbose_name='Desparasitacion'),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip',
            field=models.BooleanField(default=False, verbose_name='Microchip'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sterilization',
            field=models.BooleanField(default=False, verbose_name='Esterilización'),
        ),
    ]
