# Generated by Django 5.2.6 on 2025-09-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0008_pet_desparasitacion_pet_microchip_pet_sterilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_photo_storage_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ruta de almacenamiento de la foto de perfil'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
    ]
