# Generated by Django 5.2.6 on 2025-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0009_pet_profile_photo_storage_path_alter_pet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('pending', 'Pendiente'), ('adopted', 'Adoptado')], default='available', max_length=10, verbose_name='Estado'),
        ),
    ]
