# Generated by Django 5.2.6 on 2025-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0010_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción'),
        ),
    ]
