# Generated by Django 5.2.6 on 2025-09-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0011_alter_pet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('adopted', 'Adoptado')], default='available', max_length=10, verbose_name='Estado'),
        ),
    ]
