# Generated by Django 5.2.6 on 2025-09-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0012_alter_pet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_available_for_adoption',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='ubication',
        ),
    ]
