# Generated by Django 5.2.6 on 2025-09-20 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_comment_created_at_alter_comment_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de notificación')),
                ('type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comentario')], max_length=50, verbose_name='tipo')),
                ('message', models.CharField(max_length=255, verbose_name='mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='index.post', verbose_name='post relacionado')),
                ('referenceComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='index.comment', verbose_name='comentario relacionado')),
                ('referenceLike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='index.like', verbose_name='like relacionado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuario de la acción')),
            ],
        ),
    ]
