# Generated by Django 5.2.6 on 2025-09-20 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_notifications'),
        ('mascota', '0007_alter_pet_breed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de historia')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL de la foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='mascota.pet', verbose_name='mascota')),
            ],
        ),
    ]
