# Generated by Django 5.2.6 on 2025-09-21 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_histories_pet_alter_histories_author'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_posts', to='usuarios.userprofile', verbose_name='autor'),
        ),
    ]
