# Generated by Django 5.2.6 on 2025-09-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_storage_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta de almacenamiento de la foto'),
        ),
    ]
