# Generated by Django 5.2.6 on 2025-09-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_post_photo_storage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Contenido del post'),
        ),
    ]
