# Generated by Django 5.2.6 on 2025-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Contenido del comentario'),
        ),
    ]
